# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20170728_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='Channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Channel'),
        ),
    ]
